spring:
  cloud:
    gateway:
      routes:
        - id: farmer-service
          uri: lb://farmer-service
          predicates:
            - Path=/farmers/**

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
    discovery:
      enabled: true