spring:     
  cloud:
      gateway:
        routes:
          - id: farmer-service
            uri: //farmer-service
            predicates:
              - Path=/farmers
      
          - id: customer-service
            uri: //customer-service
            predicates:
              - Path=/customers