salary:
  minimum: 125000
  maximum: 8000000
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
